# Generated by Django 2.0.5 on 2018-06-23 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('anomaly', models.BooleanField(default=False)),
                ('validated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BridgeLog',
            fields=[
                ('log_type', models.CharField(choices=[('D', 'Damage Record'), ('R', 'Repair Record')], max_length=1)),
                ('log_time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Bridge', unique_for_date='log_time')),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='BrokenFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sensors.Bridge')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sensors.BridgeLog')),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, max_digits=4)),
                ('y', models.DecimalField(decimal_places=2, max_digits=4)),
                ('z', models.DecimalField(decimal_places=2, max_digits=4)),
                ('theta', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('psi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('time_taken', models.DateTimeField(auto_now_add=True)),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Bridge', unique_for_date='time_taken')),
            ],
            options={
                'verbose_name': 'Bridge sensor reading',
            },
        ),
    ]
