# Generated by Django 2.0.5 on 2019-04-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('calibration', models.FloatField(blank=True, default=1)),
                ('number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BridgeLog',
            fields=[
                ('log_type', models.CharField(choices=[('D', 'Damage Record'), ('R', 'Repair Record')], max_length=1)),
                ('log_time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Bridge', unique_for_date='log_time')),
            ],
            options={
                'ordering': ['bridge__name', 'log_type', '-log_time'],
            },
        ),
        migrations.CreateModel(
            name='BrokenFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sensors.Bridge')),
                ('damage_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sensors.BridgeLog')),
            ],
            options={
                'ordering': ['bridge__name'],
            },
        ),
        migrations.CreateModel(
            name='ErrorStatus',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='', max_length=80)),
            ],
            options={
                'verbose_name': 'Error Status Code',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RawReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, max_digits=6)),
                ('y', models.DecimalField(decimal_places=2, max_digits=6)),
                ('z', models.DecimalField(decimal_places=2, max_digits=6)),
                ('theta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phi', models.DecimalField(decimal_places=2, max_digits=6)),
                ('psi', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time_taken', models.DateTimeField(auto_now_add=True)),
                ('counter', models.IntegerField(default=-1)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Bridge', unique_for_date='time_taken')),
            ],
            options={
                'verbose_name': 'Bridge Sensor Raw Reading',
                'ordering': ['target__name', '-time_taken'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4)),
                ('y', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4)),
                ('z', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4)),
                ('theta', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4)),
                ('phi', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4)),
                ('psi', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4)),
                ('time_taken', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sensors.RawReading', unique_for_date='time_taken')),
            ],
            options={
                'verbose_name': 'Bridge Sensor Reading',
                'ordering': ['base__target__name', '-time_taken'],
            },
        ),
        migrations.AddField(
            model_name='errorstatus',
            name='sources',
            field=models.ManyToManyField(to='sensors.RawReading'),
        ),
        migrations.AddField(
            model_name='bridge',
            name='init_reading',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sensors.RawReading'),
        ),
    ]
