# Generated by Django 2.0.5 on 2018-06-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-time_taken'], 'verbose_name': 'Bridge sensor reading'},
        ),
    ]
