# Generated by Django 2.0.5 on 2019-04-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20190430_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='calibration',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
