# Generated by Django 2.0.5 on 2018-06-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20180623_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bridgelog',
            options={'ordering': ['-log_time', 'log_type', 'bridge__name']},
        ),
        migrations.AlterModelOptions(
            name='brokenflag',
            options={'ordering': ['bridge__name']},
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['bridge__name', '-time_taken'], 'verbose_name': 'Bridge Sensor Reading'},
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='anomaly',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='validated',
        ),
    ]
