# Generated by Django 2.0.5 on 2018-06-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20180624_0658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bridgelog',
            options={'ordering': ['bridge__name', 'log_type', '-log_time']},
        ),
        migrations.RenameField(
            model_name='brokenflag',
            old_name='record',
            new_name='first_broken_record',
        ),
    ]
