# Generated by Django 2.0.5 on 2019-04-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20190430_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawreading',
            name='phi',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rawreading',
            name='psi',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rawreading',
            name='theta',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rawreading',
            name='x',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rawreading',
            name='y',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rawreading',
            name='z',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
