# Generated by Django 2.0.5 on 2018-06-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20180626_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokenflag',
            old_name='first_broken_record',
            new_name='damage_record',
        ),
    ]
