# Generated by Django 2.0.5 on 2019-03-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20180628_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, max_digits=4)),
                ('y', models.DecimalField(decimal_places=2, max_digits=4)),
                ('z', models.DecimalField(decimal_places=2, max_digits=4)),
                ('theta', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('psi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('time_taken', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Bridge', unique_for_date='time_taken')),
            ],
            options={
                'verbose_name': 'Bridge Sensor Raw Reading',
                'ordering': ['bridge__name', '-time_taken'],
            },
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['base__bridge__name', '-time_taken'], 'verbose_name': 'Bridge Sensor Reading'},
        ),
        migrations.RemoveField(
            model_name='reading',
            name='bridge',
        ),
        migrations.AddField(
            model_name='bridge',
            name='init_reading',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sensors.RawReading'),
        ),
        migrations.AddField(
            model_name='reading',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sensors.RawReading', unique_for_date='time_taken'),
        ),
    ]
