# Generated by Django 2.0.3 on 2019-04-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20190318_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridge',
            name='calibration',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='bridge',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
