# Generated by Django 2.0.5 on 2019-05-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20190501_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='x',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
