# Generated by Django 2.0.3 on 2019-04-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20190429_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorStatus',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('sources', models.ManyToManyField(to='sensors.RawReading')),
            ],
            options={
                'verbose_name': 'Error Status Code',
                'ordering': ['code'],
            },
        ),
    ]
