# Generated by Django 2.0.5 on 2019-05-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20190501_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
