# Generated by Django 2.0.3 on 2019-04-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_test1_test2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test2',
            name='test1',
        ),
        migrations.DeleteModel(
            name='Test1',
        ),
        migrations.DeleteModel(
            name='Test2',
        ),
    ]
